spring.application.name=backend2024
spring.sql.init.schema-locations=classpath:database/schema.sql
spring.sql.init.data-locations=classpath:database/data.sql
logging.level.root=INFO
spring.sql.init.mode=never

# JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
#spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Database Connection Settings
spring.datasource.url=jdbc:postgresql://db:5432/rinhabackend2024?tcpKeepAlive=true&socketTimeout=30
spring.datasource.username=rinhabackend2024
spring.datasource.password=pwd12345678

# HikariCP Connection Pool Optimization
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=25
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=45000