spring.application.name=backend2024
spring.datasource.url=jdbc:postgresql://db:5432/rinhabackend2024
spring.datasource.username=rinhabackend2024
spring.datasource.password=pwd12345678
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.schema-locations=classpath:database/schema.sql
spring.sql.init.data-locations=classpath:database/data.sql
logging.level.root=INFO