DROP TABLE IF EXISTS tb_transaction;
DROP TABLE IF EXISTS tb_clients;

CREATE TABLE tb_clients (
    id BIGSERIAL NOT NULL,
    saldo INTEGER NOT NULL,
    limite INTEGER NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE tb_transaction (
    id_transaction BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_client BIGINT,
    valor INTEGER NOT NULL,
    tipo CHAR(1),
    descricao VARCHAR(255),
    realizada_em TIMESTAMP(6),
    FOREIGN KEY (id_client) REFERENCES tb_clients(id)
);